(newline)
(load "proj4-ab1.scm")
(newline)
(load "proj4-a1.scm")
(newline)
(load "proj4-b1.scm")
(newline)
(load "proj4-ab2.scm")
(newline)
(load "proj4-a2.scm")
(newline)
(load "proj4-b2.scm")
(newline)
(load "proj4-ab3.scm")
(newline)
(print-test-results)
(exit)
